### ISSUE TITLE
Setting for HTTPS

### ISSUE THREAD

**Issue by mayjolux** [opendatateam/csvapi#18]
We are trying to use the csvapi for the udata-tabular-preview, we already have deployed it successfully as a docker container and is available under the following link http://csvapi.data.public.lu. When we try to visualise a csv dataset, the request is made via an HTTPS request and returns successfully the result object via the csvapi, but the requested URL is HTTP which blocks the visualisation due to requesting an insecure resource.

Is there a possibility/setting option to guarantee an HTTPS request when the object is returned via the csvapi?

**Comment by abulte** [comment]
Hi,

Great news! If you set `TABULAR_CSVAPI_URL` to an https URL, it should do the trick (cf https://github.com/opendatateam/udata-tabular-preview/blob/master/udata_tabular_preview/preview.py#L20).

**Comment by mayjolux** [comment]
Hi, thanks for the help!

But even now the returned URL of the csvapi returns the result as an http URL as seen here:
<img width="716" alt="Screenshot 2019-06-07 at 07 47 44" src="https://user-images.githubusercontent.com/46596744/59083784-fbd7c680-88f8-11e9-9621-12b435ff7053.png">

**Comment by abulte** [comment]
You can try `FORCE_SSL`: https://github.com/opendatateam/csvapi/blob/d0c0f915ce8d73e423ef95d5be521f6d873875c5/config.py#L6

**Comment by abulte** [comment]
Hope this helps! Feel free to reopen the issue if it does not.
